{
    "test_file": "Create_Testing_in_Software_Development/test_python_software.py",
    "timestamp": "2024-09-01T20:20:17.023373",
    "status": "failure",
    "details": "============================= test session starts =============================\nplatform win32 -- Python 3.9.1, pytest-8.3.2, pluggy-1.5.0\nrootdir: C:\\Users\\ualer\\Downloads\\Saas do site\\A-I-O-R-G\nplugins: anyio-4.3.0, dash-2.14.2, Faker-22.4.0, json-report-1.5.0, metadata-3.1.1, typeguard-4.2.1\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_ ERROR collecting Create_Testing_in_Software_Development/test_python_software.py _\nImportError while importing test module 'C:\\Users\\ualer\\Downloads\\Saas do site\\A-I-O-R-G\\Create_Testing_in_Software_Development\\test_python_software.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py:127: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nCreate_Testing_in_Software_Development\\test_python_software.py:4: in <module>\n    from Create_Testing_in_Software_Development.python_software import download_vods, main  # Substitua 'your_module' pelo nome do m\u00f3dulo onde est\u00e1 o c\u00f3digo\nE   ModuleNotFoundError: No module named 'Create_Testing_in_Software_Development'\n=========================== short test summary info ===========================\nERROR Create_Testing_in_Software_Development/test_python_software.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 1.27s ===============================\n"
}